# Generated by Django 5.1.4 on 2025-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_secret_key', models.IntegerField()),
                ('otp_valid_date', models.DateField()),
            ],
        ),
    ]
