# Generated by Django 5.1.4 on 2025-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpbank',
            name='key_user',
            field=models.CharField(default=4325353, max_length=100),
            preserve_default=False,
        ),
    ]
