# Generated by Django 5.1.4 on 2025-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpbank_key_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpbank',
            name='otp_secret_key',
            field=models.CharField(max_length=50),
        ),
    ]
