# Generated by Django 5.1.4 on 2025-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otpbank_otp_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpbank',
            name='otp_valid_date',
            field=models.DateTimeField(),
        ),
    ]
