# Generated by Django 5.1.4 on 2025-01-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='athleteRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('eventName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='raceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('raceType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('regStartDate', models.DateField(blank=True, null=True)),
                ('regEndDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
