# Generated by Django 5.1.4 on 2025-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_athleteregistration_registratiodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteregistration',
            name='bibNumber',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='athleteregistration',
            name='eventCategory',
            field=models.IntegerField(default=0),
        ),
    ]
